// <auto-generated />
using System;
using EMS.CORE;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.CORE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326043750_nhat_update")]
    partial class nhat_update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("ORDER_SEQUENCE");

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("ACTION_URL");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("RequestData")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("REQUEST_DATA");

                    b.Property<DateTime?>("RequestTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("REQUEST_TIME");

                    b.Property<string>("ResponseData")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("RESPONSE_DATA");

                    b.Property<DateTime?>("ResponseTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("RESPONSE_TIME");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int")
                        .HasColumnName("STATUS_CODE");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UserName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.ToTable("T_AD_ACTIONLOG");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccount", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("USER_NAME");

                    b.Property<string>("AccountType")
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("ACCOUNT_TYPE");

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("DELETE_BY");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FaceId")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("FACE_ID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("FULL_NAME");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("OrganizeCode")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("ORG_CODE");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UrlImage")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("URL_IMAGE");

                    b.Property<string>("UserId")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("USER_ID");

                    b.HasKey("UserName");

                    b.ToTable("T_AD_ACCOUNT");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccountGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("DELETE_BY");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("Notes")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("NOTES");

                    b.Property<string>("RoleCode")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("ROLE_CODE");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Id");

                    b.ToTable("T_AD_ACCOUNTGROUP");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccountGroupRight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("DELETE_BY");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GROUP_ID");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("RightId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("RIGHT_ID");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RightId");

                    b.ToTable("T_AD_ACCOUNTGROUP_RIGHT");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccountRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("EXPIRE_TIME");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(2000)")
                        .HasColumnName("REFRESH_TOKEN");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.HasIndex("UserName");

                    b.ToTable("T_AD_REFRESH_TOKEN");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccountRight", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("USER_NAME");

                    b.Property<string>("RightId")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("RIGHT_ID");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool?>("IsAdded")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ADDED");

                    b.Property<bool?>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("IS_REMOVED");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("UserName", "RightId");

                    b.HasIndex("RightId");

                    b.ToTable("T_AD_ACCOUNT_RIGHT");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccountStore", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("USER_NAME");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("StoreCode")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("STORE_CODE");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("UserName");

                    b.HasIndex("StoreCode");

                    b.ToTable("T_AD_ACCOUNT_STORE");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccount_AccountGroup", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("USER_NAME");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GROUP_ID");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("UserName", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("T_AD_ACCOUNT_ACCOUNTGROUP");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAppVersion", b =>
                {
                    b.Property<int>("VersionCode")
                        .HasColumnType("int")
                        .HasColumnName("VERSION_CODE");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("IsRequiredUpdate")
                        .HasColumnType("bit")
                        .HasColumnName("IS_REQUIRED_UPDATE");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("VERSION_NAME");

                    b.HasKey("VersionCode");

                    b.ToTable("T_AD_APP_VERSION");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdMenu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("ID");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("DELETE_BY");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("Icon")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("ICON");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("NAME");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("ORDER_NUMBER");

                    b.Property<string>("PId")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("P_ID");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("Url")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("URL");

                    b.HasKey("Id");

                    b.ToTable("T_AD_MENU");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdMenuRight", b =>
                {
                    b.Property<string>("MenuId")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("RightId")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("MenuId", "RightId");

                    b.HasIndex("RightId");

                    b.ToTable("T_AD_MENU_RIGHT");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdMessage", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("CODE");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("DELETE_BY");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("LANG");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("VALUE");

                    b.HasKey("Code");

                    b.ToTable("T_AD_MESSAGE");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdRight", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("DELETE_BY");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("ORDER_NUMBER");

                    b.Property<string>("PId")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Id");

                    b.ToTable("T_AD_RIGHT");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdSystemTrace", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<int>("InterVal")
                        .HasColumnType("int")
                        .HasColumnName("INTERVAL");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<DateTime?>("LastCheckTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LAST_CHECK_TIME");

                    b.Property<string>("Log")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LOG");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NOTE");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TYPE");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Code");

                    b.ToTable("T_AD_SYSTEM_TRACE");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.tblAdOrganize", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("DELETE_BY");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("ORDER_NUMBER");

                    b.Property<string>("PId")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Id");

                    b.ToTable("T_AD_ORGANIZE");
                });

            modelBuilder.Entity("EMS.CORE.Entities.CM.TblCmFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("ID");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("DELETE_BY");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("FileName")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("FILE_NAME");

                    b.Property<string>("FileNameKhongDau")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("FILE_NAME_KHONG_DAU");

                    b.Property<string>("FilePath")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("PATH");

                    b.Property<string>("FilePathFull")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("FILE_PATH");

                    b.Property<decimal?>("FileSize")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("FILE_SIZE");

                    b.Property<string>("FileType")
                        .HasColumnType("NVARCHAR(200)")
                        .HasColumnName("FILE_TYPE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool?>("IsAllowDelete")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ALLOW_DELETE");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("RefrenceFileId")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("REFRENCE_FILE_ID");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Id");

                    b.ToTable("T_CM_FILE");
                });

            modelBuilder.Entity("EMS.CORE.Entities.MD.TblMdAccountType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Code");

                    b.ToTable("T_MD_ACCOUNT_TYPE");
                });

            modelBuilder.Entity("EMS.CORE.Entities.MD.TblMdEmployees", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("DigitalSig")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("DIGITALSIG");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("FULL_NAME");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("PHONENUMBER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("POSITION");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Code");

                    b.ToTable("T_MD_EMPLOYEES");
                });

            modelBuilder.Entity("EMS.CORE.Entities.MD.TblMdPriority", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Code");

                    b.ToTable("T_MD_PRIORITY");
                });

            modelBuilder.Entity("EMS.CORE.Entities.MD.TblMdStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Code");

                    b.ToTable("T_MD_STATUS");
                });

            modelBuilder.Entity("EMS.CORE.Entities.MD.TblMdStore", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("AREA");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("DELETE_BY");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELETE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Phone")
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("PHONE");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Code");

                    b.ToTable("T_MD_STORE");
                });

            modelBuilder.Entity("EMS.CORE.Entities.MD.TblMdTest", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Code");

                    b.ToTable("T_MD_TEST");
                });

            modelBuilder.Entity("EMS.CORE.Entities.MD.TblMdTest2", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Code");

                    b.ToTable("T_MD_TEST_2");
                });

            modelBuilder.Entity("EMS.CORE.Entities.MD.TblMdUnit", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATE_DATE");

                    b.HasKey("Code");

                    b.ToTable("T_MD_UNIT");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccountGroupRight", b =>
                {
                    b.HasOne("EMS.CORE.Entities.AD.TblAdAccountGroup", "AccountGroup")
                        .WithMany("ListAccountGroupRight")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.CORE.Entities.AD.TblAdRight", "Right")
                        .WithMany("AccountGroupRights")
                        .HasForeignKey("RightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountGroup");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccountRefreshToken", b =>
                {
                    b.HasOne("EMS.CORE.Entities.AD.TblAdAccount", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccountRight", b =>
                {
                    b.HasOne("EMS.CORE.Entities.AD.TblAdRight", "Right")
                        .WithMany("AccountRights")
                        .HasForeignKey("RightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.CORE.Entities.AD.TblAdAccount", "Account")
                        .WithMany("AccountRights")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccountStore", b =>
                {
                    b.HasOne("EMS.CORE.Entities.MD.TblMdStore", "TblMdStore")
                        .WithMany("AccountStores")
                        .HasForeignKey("StoreCode");

                    b.HasOne("EMS.CORE.Entities.AD.TblAdAccount", "TblAdAccount")
                        .WithOne("AccountStores")
                        .HasForeignKey("EMS.CORE.Entities.AD.TblAdAccountStore", "UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TblAdAccount");

                    b.Navigation("TblMdStore");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccount_AccountGroup", b =>
                {
                    b.HasOne("EMS.CORE.Entities.AD.TblAdAccountGroup", "AccountGroup")
                        .WithMany("Account_AccountGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.CORE.Entities.AD.TblAdAccount", "Account")
                        .WithMany("Account_AccountGroups")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("AccountGroup");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdMenuRight", b =>
                {
                    b.HasOne("EMS.CORE.Entities.AD.TblAdMenu", "Menu")
                        .WithMany("RightReferences")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.CORE.Entities.AD.TblAdRight", "Right")
                        .WithMany()
                        .HasForeignKey("RightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccount", b =>
                {
                    b.Navigation("AccountRights");

                    b.Navigation("AccountStores")
                        .IsRequired();

                    b.Navigation("Account_AccountGroups");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdAccountGroup", b =>
                {
                    b.Navigation("Account_AccountGroups");

                    b.Navigation("ListAccountGroupRight");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdMenu", b =>
                {
                    b.Navigation("RightReferences");
                });

            modelBuilder.Entity("EMS.CORE.Entities.AD.TblAdRight", b =>
                {
                    b.Navigation("AccountGroupRights");

                    b.Navigation("AccountRights");
                });

            modelBuilder.Entity("EMS.CORE.Entities.MD.TblMdStore", b =>
                {
                    b.Navigation("AccountStores");
                });
#pragma warning restore 612, 618
        }
    }
}
